package com.ocms.project.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ocms.project.model.Grade;
import com.ocms.project.model.Report;
import com.ocms.project.repository.GradeRepository;
import com.ocms.project.repository.ReportRepository;
import com.ocms.project.repository.UserRepository;

/**
 * ReportGenerator - Admin Report Generation Service
 * Uses Template Method Pattern for different report types
 */
@Service
public class ReportGenerator {

    @Autowired
    private ReportRepository reportRepository;

    @Autowired
    private GradeRepository gradeRepository;

    @Autowired
    private UserRepository userRepository;

    public Report generateStudentPerformanceReport(Long adminId, Long studentId) {
        Report report = new Report("STUDENT_PERFORMANCE", adminId);
        List<Grade> grades = gradeRepository.findByStudentId(studentId);
        
        StringBuilder content = new StringBuilder();
        content.append("Student Performance Report\n");
        content.append("Student ID: ").append(studentId).append("\n");
        content.append("Total Courses: ").append(grades.size()).append("\n");
        
        double avgMarks = grades.stream().mapToDouble(Grade::getMarksObtained).average().orElse(0);
        content.append("Average Marks: ").append(String.format("%.2f", avgMarks)).append("\n");
        
        report.setReportContent(content.toString());
        report.setStudentId(studentId);
        return reportRepository.save(report);
    }

    public Report generateCourseAnalyticsReport(Long adminId, Long courseId) {
        Report report = new Report("COURSE_ANALYTICS", adminId);
        List<Grade> grades = gradeRepository.findByCourseId(courseId);
        
        StringBuilder content = new StringBuilder();
        content.append("Course Analytics Report\n");
        content.append("Course ID: ").append(courseId).append("\n");
        content.append("Total Students: ").append(grades.size()).append("\n");
        
        long passCount = grades.stream().filter(g -> g.getGradeStatus().equals("PASS")).count();
        content.append("Pass Rate: ").append(String.format("%.2f%%", (passCount * 100.0 / grades.size()))).append("\n");
        
        report.setReportContent(content.toString());
        report.setCourseId(courseId);
        return reportRepository.save(report);
    }

    public Report generateEnrollmentStatisticsReport(Long adminId) {
        Report report = new Report("ENROLLMENT_STATS", adminId);
        
        StringBuilder content = new StringBuilder();
        content.append("Enrollment Statistics Report\n");
        content.append("Total Users: ").append(userRepository.count()).append("\n");
        content.append("Report Generated By: Admin ").append(adminId).append("\n");
        
        report.setReportContent(content.toString());
        return reportRepository.save(report);
    }

    public List<Report> getAdminReports(Long adminId) {
        return reportRepository.findByGeneratedBy(adminId);
    }

    public List<Report> getReportsByType(String reportType) {
        return reportRepository.findByReportType(reportType);
    }
}